name: Development
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # The targets should match the platforms on the package's Yggdrasil build recipe:
          # https://github.com/JuliaPackaging/Yggdrasil/blob/e8a9f04d70652738c682407b9799ada044d24614/O/object_store_ffi/build_tarballs.jl#L20
          # 64-bit (x86)
          - build: linux-64-bit
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            prebuild: "true"
            command: cross
          - build: macos-64-bit
            os: macos-latest
            target: x86_64-apple-darwin
            prebuild: "true"
            command: cargo
          # 64-bit (ARM)
          - build: linux-arm
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            prebuild: "true"
            command: cross
          - build: macos-arm
            os: macos-latest
            target: aarch64-apple-darwin
            prebuild: "true"
            command: cargo
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.target }}
      - run: cargo install cross --git https://github.com/cross-rs/cross
      - run: ${{ matrix.prebuild }}
      - run: ${{ matrix.command }} build --release --target ${{ matrix.target }}
